// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtM1zqJjFCXR9ISLf9QXtPpUT7HvAm5mE',
    appId: '1:622403882222:web:0bd177626b311ad47c77ff',
    messagingSenderId: '622403882222',
    projectId: 'inspiredgrow-prod',
    authDomain: 'inspiredgrow-prod.firebaseapp.com',
    storageBucket: 'inspiredgrow-prod.firebasestorage.app',
    measurementId: 'G-TM51PDXJFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4-FJTOJ9DPv7IlXKtOTgNv7LYinkpoLM',
    appId: '1:622403882222:android:59cdfa98458650b37c77ff',
    messagingSenderId: '622403882222',
    projectId: 'inspiredgrow-prod',
    storageBucket: 'inspiredgrow-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1FWHUZV38w1EHv3ZsXTiSwjtRzFiTRtg',
    appId: '1:622403882222:ios:c2543eb36e8260817c77ff',
    messagingSenderId: '622403882222',
    projectId: 'inspiredgrow-prod',
    storageBucket: 'inspiredgrow-prod.firebasestorage.app',
    iosBundleId: 'com.anshul.eshop',
  );

}